### ISSUE TITLE
Кикает

### ISSUE THREAD

**Issue by Klatch13** [27rogi/Fabric2Discord#12]
Когда отправляешь какое-либо сообщение из майнкрафта, то кикает

**Comment by Klatch13** [comment]
![unknown.png](https://user-images.githubusercontent.com/108920477/186473922-33ae4697-95a3-4e88-a622-a18672417d0a.png)

**Comment by Klatch13** [comment]
Хотя скорее всего это не из за вашего мода

**Comment by 27rogi** [comment]
Будет хорошо если укажите полный лог, так как ошибки на стороне клиента быть из-за F2D по логике не может т.к. это мод исключительно для сервера.

**Comment by Klatch13** [comment]
В консоль ничего не писалось когда кикало

**Comment by 27rogi** [comment]
> В консоль ничего не писалось когда кикало

В консоль ничего и не будет писать, это ошибка на стороне клиента

**Comment by Klatch13** [comment]
Проблема была в моде SimplerAuth

**Comment by Klatch13** [comment]
Можно меня вас попросить добавить совместимость с модом Vanish.
Просто когда я пишу /Vanish, то в чате майнкрафта пишет что я вышел из игры, а в чате дискорд нет

**Comment by Klatch13** [comment]
Или мне надо обратится к создателю мода Vanish?

**Comment by 27rogi** [comment]
> Можно меня вас попросить добавить совместимость с модом Vanish. Просто когда я пишу /Vanish, то в чате майнкрафта пишет что я вышел из игры, а в чате дискорд нет

Такое может быть в случае отправки обычного "фейкового" сообщения о выходе, мой мод работает на Миксинах и напрямую добавляет доп. код в функцию, отвечающую за выход игрока с сервера.
