### ISSUE TITLE
no message from discord to minecraft

### ISSUE THREAD

**Issue by Ai-Kiwi** [27rogi/Fabric2Discord#18]
hello for some reason my messages are not appearing in minecraft when i send a message in discord but when i send a message in minecraft they do appear in discord. Is this a feature or a bug? also im not sure if it helps but the bot also is not appearing to be online at all.

**Comment by 27rogi** [comment]
> hello for some reason my messages are not appearing in minecraft when i send a message in discord but when i send a message in minecraft they do appear in discord. Is this a feature or a bug? also im not sure if it helps but the bot also is not appearing to be online at all.

Something is wrong with your bot configuration, be sure to follow the guidelines in Wiki.

**Comment by Ai-Kiwi** [comment]
> Something is wrong with your bot configuration, be sure to follow the guidelines in Wiki.

yes turns out there was a setting i missed and the bot is now running perfectly
