### ISSUE TITLE
Unable to disable dimension messages

### ISSUE THREAD

**Issue by arconyx** [27rogi/Fabric2Discord#2]
Disabling the dimension change message by setting enabled to false has no apparent effect. A message is still sent whenever players change dimensions.
```
    playerDimension {
        color="#b967ff"
        enabled=false
        footer="Previous location is %world_origin%"
        header="%player:name% has teleported to %player:world%"
        iconFooter=""
        iconHeader="https://minotar.net/cube/%player:name%/100.png"
        image=""
        message=""
        timestamp=false
    }
```

**Comment by 27rogi** [comment]
Seems like the problem is inside the code, same with #3 
Will try to fix this soon.

**Comment by n1ckoates** [comment]
As a temporary fix, I built a version of the mod with dimension switch messages completely removed
https://cdn.discordapp.com/attachments/845088637527785514/999731378033791057/Fabric2Discord-1.0.21.19-NO-DIMENSION-SWITCH.jar
