### ISSUE TITLE
[1.18.2] Discord to Minecraft default chat format config not working as intented

### ISSUE THREAD

**Issue by Abaan404** [27rogi/Fabric2Discord#20]
Hi! I have used your mod before and wanted to use it again for a modded fabric server however on the default configs, the discord -> fabric formatting doesn't seem to be working properly

`format="[<color:4ae485>F2D</color>] %discord_user%<gray>#%discord_tag%</gray>: "`

results in 
![image](https://user-images.githubusercontent.com/67100191/221429073-3379fb36-96e4-4b44-8a12-9e57cfb95818.png)

Not sure why this is happening, any advice would be appreciated :)
version `f2d 2.1.0+1.18.2`
Thanks

**Comment by 27rogi** [comment]
Could you try to use different strings in formatting? For example without any formatting tags, maybe they are causing the issue.

**Comment by Abaan404** [comment]
Using this string, discord messages dont show up anymore in chat
![image](https://user-images.githubusercontent.com/67100191/221438125-18c4d98a-691e-4b07-ac06-b7a1cf749430.png)

**Comment by 27rogi** [comment]
Weird, maybe something changed in newer Fabric versions, will try to reproduce and hopefully fix this issue.
