### ISSUE TITLE
[1.19.3 Bug] Messages stop showing after sending an empty message

### ISSUE THREAD

**Issue by Greyberet** [27rogi/Fabric2Discord#21]
If you send an empty message on discord or minecraft, such as "** **", messages will stop showing until I restart the server

[log.txt](https://github.com/rogi27/Fabric2Discord/files/10893509/log.txt)

![image](https://user-images.githubusercontent.com/58717769/222997999-e881b20d-0b1e-43f5-891e-8000cadc14ef.png)

![image](https://user-images.githubusercontent.com/58717769/222998014-2816ba41-df10-4798-a6aa-8d9e6851a8af.png)

**Comment by 27rogi** [comment]
I tested it on latest updated version for 1.19.4 and was unable to reproduce this bug, so I think it's solved.
