### ISSUE TITLE
Can't use server emoji in Header

### ISSUE THREAD

**Issue by ZUIXIIDE** [27rogi/Fabric2Discord#26]
I tried with both ID and with colons and name of emoji it's show as plain text

**Comment by 27rogi** [comment]
As far as I know this is a Discord limitation, you might want to try to directly use emoji symbols, like this one `⭐️`.

**Comment by ZUIXIIDE** [comment]
Thank you.

ในวันที่ จ. 1 พ.ค. 2023 01:11 น. Igor Ryzhenkov ***@***.***>
เขียนว่า:
