### ISSUE TITLE
Fabric2discord  f2d failed injection check, (0/1) succeeded.

### ISSUE THREAD

**Issue by Generalgeo63** [27rogi/Fabric2Discord#44]
Running on 1.19 and have fabric loader 0.14.25 and using the latest release of this mod for my really big server unfortunately ive tried resolving myself as best as i can to search this issue but cant get it resolved kinda at a dead end and not sure what to do . to keep it short the only error sticking out in my server console was solely this issue Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method afterSetupServer(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in f2d.mixins.json:MinecraftServerMixin from mod f2d failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Fabric2Discord-refmap.json .  Wasnt sure if this mod can get in conflict with any others. EDIT . Apologies found a new error while scrolling through ixin apply for mod f2d failed f2d.mixins.json:ServerPlayNetworkHandlerMixin from mod f2d -> net.minecraft.class_3244: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onPlayerMessageEvent could not find any targets matching 'Lnet/minecraft/class_3244;method_44155(Lnet/minecraft/class_7471;)V' in net.minecraft.class_3244. Using refmap Fabric2Discord-refmap.json [PREINJECT Applicator Phase -> f2d.mixins.json:ServerPlayNetworkHandlerMixin from mod f2d -> Prepare Injections ->  -> handler$bjg000$f2d$onPlayerMessageEvent(Lnet/minecraft/class_7471;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

**Comment by 27rogi** [comment]
This mod only works for 1.19.3 and 1.19.4

**Comment by Generalgeo63** [comment]
> This mod only works for 1.19.3 and 1.19.4

On curse forge it says it works for 1.19 but understandable thank you for the quick response
