### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MayaqqDev** [27rogi/Fabric2Discord#9]
[latest.log](https://github.com/rogi27/Fabric2Discord/files/9389684/latest.log)

**Comment by RealAnthony0001** [comment]
I had similar issue. Fixed it by making the bot administrator. Idk if this is the best solution but it worked.

**Comment by MayaqqDev** [comment]
Alright will try

**Comment by 27rogi** [comment]
This error occurs when your bot doesn't have enough permissions on the server, also be sure to check all switches in Gateway Intents on Discord Developer Portal.
